language: java
jdk: 
- oraclejdk14
cache: 
  directories: 
  - $HOME/.m2
os: linux
dist: focal
arch: arm64
git:
  quiet: true
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
services:
- mysql
install: echo "skip install"
before_script:
- mysql < scriptDatabase/DB.sql
- mysql -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}';"
- mysql -e "GRANT ALL ON MensaDigitale.* to '${MYSQL_USER}'@'localhost';"
- mysql -u"$MYSQL_USER" -p"$MYSQL_PASS" -e "USE MensaDigitale; SHOW tables;"
notifications: 
- slack: progettois-2020:CCvmGg5hbeqP1azu8n956S4p
script:
- mvn test -B jacoco:report
- bash ./scriptTravis.sh
