language: java
jdk: 
- oraclejdk14
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
services:
- mysql
before_script:
- mysql -u root -e "CREATE DATABASE MensaDigitale;"
- mysql -u root -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}';"
- mysql -u root -e "GRANT ALL ON MensaDigitale.* to '${MYSQL_USER}'@'localhost';"
- mysql -u root -e "select * from mysql.user;"