language: java
jdk: 
- oraclejdk14
cache: 
  directories: 
  - $HOME/.m2
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
services:
- mysql
before_script:
- mysql -u root < scriptDatabase/DB.sql
- mysql -u root -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}';"
- mysql -u root -e "GRANT ALL ON MensaDigitale.* to '${MYSQL_USER}'@'localhost';"
- mysql -u"$MYSQL_USER" -p"$MYSQL_PASS" -e "USE MensaDigitale; SHOW tables;"
notifications: 
- slack: progettois-2020:CCvmGg5hbeqP1azu8n956S4p
jobs:
  include:
    - stage: business.prenotazioni
      script: mvn -Dtest=business.prenotazioni test
      stage: business.piatti
      script: mvn -Dtest=business.piatti test
