language: java
sudo: false
jdk: 
- oraclejdk14
cache: 
  directories: 
  - $HOME/.m2
os: linux
dist: focal
arch: arm64
env:
  global:
    - CODECOV_TOKEN=$CODECOV_UUID_REPO
git:
  quiet: true
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull
services:
- mysql
install: echo "skip install"
before_script:
- mysql -u root < scriptDatabase/DB.sql
- mysql -u root -e "CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}';"
- mysql -u root -e "GRANT ALL ON MensaDigitale.* to '${MYSQL_USER}'@'localhost';"
- mysql -u"$MYSQL_USER" -p"$MYSQL_PASS" -e "USE MensaDigitale; SHOW tables;"
after_success: 
  - bash <(curl -s https://codecov.io/bash)
notifications: 
- slack: progettois-2020:CCvmGg5hbeqP1azu8n956S4p
