on:
  push:
    branches: [ main ]   
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql: 
        image: mysql:8.0.22
        env: 
          MYSQL_ROOT_PASSWORD: password 
        ports:
        - 3306 
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:        
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 14
    - name: MySql setup
      run: |
        sudo /etc/init.d/mysql start
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword < scriptDatabase/DB.sql
        echo "script done"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "CREATE USER 'esame'@'127.0.0.1' IDENTIFIED BY 'esame';"
        echo "user created"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "GRANT ALL ON MensaDigitale.* to 'esame'@'127.0.0.1'; flush privileges;"
        echo "granted permissions"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "select host, user from mysql.user"
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "show grants for 'esame'@'127.0.0.1';"
        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
