on:
  push:
    branches: [ main ]   
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:8.0.22
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mvn:
        image: maven
    steps:        
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 14  
    - name: MySql setup
      run: |
        apt-get update && apt-get install -y mysql-client
        mysql --host mysql -uroot -ppassword < scriptDatabase/DB.sql
        echo "script done"
        mysql --host mysql -uroot -ppassword -e "CREATE USER 'esame'@'localhost' IDENTIFIED BY 'esame';"
        echo "user created"
        mysql --host mysql -uroot -ppassword -e "GRANT ALL ON MensaDigitale.* to 'esame'@'localhost';"
        echo "granted permissions"
        mysql --host mysql -uroot -ppassword -e "select host, user from mysql.user"
    - name: Cache Maven packages 
      uses: actions/cache@v2 
      with: 
        path: ~/.m2 
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} 
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
